---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.2
  - name: fedora-22
  - name: debian-7.11
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[cop_varnish::default]
